WebApplicationCoreGLSI-C/Controllers/CategorieController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplicationCoreGLSI_C.Models;

namespace WebApplicationCoreGLSI_C.Controllers
{
    public class CategorieController : Controller
    {
        private readonly AppDbContext _db;
        public CategorieController(AppDbContext _db)
        {
            this._db = _db;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _db.categories.ToListAsync());
        }
        public IActionResult DownLoadFile()
        {
            byte[] bytes = System.IO
                .File.ReadAllBytes(@"C:\Users\TEK-UP\Desktop\Document.pdf");
            return File(bytes, "application/pdf");

        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Categorie categorie)
        {
            _db.categories.Add(categorie);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public IActionResult Edit(Guid? id)
        {
            if(id== null) return NotFound();
            var categorie = _db.categories.FirstOrDefault(c => c.Id==id);
            return View(categorie);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Categorie cat)
        {
            _db.categories.Update(cat);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index));

        }
        [HttpGet]
        public IActionResult Delete(Guid? id)
        {
            if (id == null) return NotFound();
            var c = _db.categories.Find(id);
            return View(c);
            //_db.categories.Remove(c);
            //_db.SaveChanges();
            //return RedirectToAction("Index");
        }
        [HttpPost]
        [ActionName("Delete")]
        public IActionResult DeleteConfirmed(Guid? id)
        {
            var c = _db.categories.Find(id);
            _db.categories.Remove(c);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

WebApplicationCoreGLSI-C/Controllers/ProduitController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplicationCoreGLSI_C.Models;
using WebApplicationCoreGLSI_C.Models.ViewModel;

namespace WebApplicationCoreGLSI_C.Controllers
{
    public class ProduitController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment webHostEnvironment;
        public ProduitController(AppDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            this.webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {
            var p = _context.produits.ToList();
            return View(p);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult Create( ProduitVM model, IFormFile photo)
        {
            if (photo == null) return Content("Photo not uploaded");

            try
            {

                var path = Path.Combine(webHostEnvironment.
                    WebRootPath, "Images", photo.FileName);
                using (FileStream stream = new FileStream(path, FileMode.Create))
                {
                    photo.CopyTo(stream);
                    stream.Close();
                }

               // model.produit.FileImage = photo.FileName;

                //Mapping manuel (automatique-->automapper)

                var produit = new Produit
                {
                    Id = new Guid(),
                    Name = model.produit.Name,

                    FileImage = photo.FileName,

                };
                _context.Add(produit);
                _context.SaveChanges();

                return RedirectToAction(nameof(Index));

            }
            catch (Exception)
            {
                throw;
            }
           
        }
    }
}

WebApplicationCoreGLSI-C/Controllers/SousCategorieController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplicationCoreGLSI_C.Models;

namespace WebApplicationCoreGLSI_C.Controllers
{
    public class SousCategorieController : Controller
    {
        private readonly AppDbContext appDbContext;
        public SousCategorieController(AppDbContext appDbContext)
        {
            this.appDbContext = appDbContext;
        }
        public async Task<IActionResult> Index()
        {
            var c = await appDbContext.sscategories.Include(c=>c.categorie).ToListAsync();
            return View(c);
        }
        public IActionResult Create()
        {
            var c = appDbContext.categories.ToList();
            ViewBag.Categories = c.Select(c =>
                new SelectListItem
                {
                    Text = c.Name,
                    Value = c.Id.ToString(),
                });
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(SousCategorie sousCategorie)
        {
            if(!ModelState.IsValid)
            {
                var c = appDbContext.categories.ToList();
                ViewBag.Categories = c.Select(c =>
                    new SelectListItem
                    {
                        Text = c.Name,
                        Value = c.Id.ToString(),
                    });
                return View();
            }
            sousCategorie.Id = Guid.NewGuid();
            appDbContext.sscategories.Add(sousCategorie);
            appDbContext.SaveChanges();
            return RedirectToAction(nameof(Index));

        }
       
    }
}

WebApplicationCoreGLSI-C/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplicationCoreGLSI_C</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplicationCoreGLSI_C.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
      <partial name="_NavBar"/>
       
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebApplicationCoreGLSI_C - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApplicationCoreGLSI-C/Views/Shared/_NavBar.cshtml
@if(User.Identity.IsAuthenticated)
{
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container-fluid">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplicationCoreGLSI_C</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Categorie" asp-action="Index">Categorie</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="SousCategorie" asp-action="Index">SousCategorie</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Produit" asp-action="Index">Produit</a>
                </li>
            </ul>
        </div>
     
    </div>
</nav>
    
}
<partial name="_LoginPartial" />